[features]
seeds = false
skip-lint = false

[programs.localnet]
carbon_certificate_oapp = "6DTmAjesQy49eeZPR3iQ4ZKPHzUU9uAsRzCuD9uGbHfw"
carbon_credit_oft = "3HZeL7L5Ep7QAe4FLnti4NfinLxLF2xb73FfRCfhf1zk"

[programs.devnet]
carbon_certificate_oapp = "6DTmAjesQy49eeZPR3iQ4ZKPHzUU9uAsRzCuD9uGbHfw"
carbon_credit_oft = "3HZeL7L5Ep7QAe4FLnti4NfinLxLF2xb73FfRCfhf1zk"

[programs.mainnet]
carbon_certificate_oapp = "6DTmAjesQy49eeZPR3iQ4ZKPHzUU9uAsRzCuD9uGbHfw"
carbon_credit_oft = "3HZeL7L5Ep7QAe4FLnti4NfinLxLF2xb73FfRCfhf1zk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[toolchain]
anchor_version = "0.29.0"

[[test.genesis]]
address = "6DTmAjesQy49eeZPR3iQ4ZKPHzUU9uAsRzCuD9uGbHfw"
program = "target/deploy/carbon_certificate_oapp.so"

[[test.genesis]]
address = "3HZeL7L5Ep7QAe4FLnti4NfinLxLF2xb73FfRCfhf1zk"
program = "target/deploy/carbon_credit_oft.so"